export interface SampleAlbum {
  id: string
  title: string
  artist: string[]
  releaseDate: Date
  releaseYear: number
  length: string
  numSongs: number
  genres: string[]
  coverImageUrl: string
  tracklist: string[]
  description?: string
  averageRating?: number
  reviewCount?: number
}

export const SAMPLE_ALBUMS: SampleAlbum[] = [
  {
    id: 'album-tpab',
    title: 'To Pimp a Butterfly',
    artist: ['Kendrick Lamar'],
    releaseDate: new Date('2015-03-15'),
    releaseYear: 2015,
    length: '78:51',
    numSongs: 16,
    genres: ['Hip Hop', 'Jazz Rap', 'Conscious Hip Hop', 'Funk'],
    coverImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'Wesley\'s Theory',
      'For Free? (Interlude)',
      'King Kunta',
      'Institutionalized',
      'These Walls',
      'u',
      'Alright',
      'For Sale? (Interlude)',
      'Momma',
      'Hood Politics',
      'How Much a Dollar Cost',
      'Complexion (A Zulu Love)',
      'The Blacker the Berry',
      'You Ain\'t Gotta Lie (Momma Said)',
      'i',
      'Mortal Man',
    ],
    averageRating: 9.8,
    reviewCount: 42,
    description: 'A sprawling masterpiece of modern jazz rap, exploring race, survivor guilt, and self-worth.',
  },
  {
    id: 'album-blonde',
    title: 'Blonde',
    artist: ['Frank Ocean'],
    releaseDate: new Date('2016-08-20'),
    releaseYear: 2016,
    length: '60:08',
    numSongs: 17,
    genres: ['R&B', 'Art Pop', 'Neo-Soul', 'Ambient'],
    coverImageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'Nikes',
      'Ivy',
      'Pink + White',
      'Be Yourself',
      'Solo',
      'Skyline To',
      'Self Control',
      'Good Guy',
      'Nights',
      'Solo (Reprise)',
      'Pretty Sweet',
      'Facebook Story',
      'Close to You',
      'White Ferrari',
      'Seigfried',
      'Godspeed',
      'Futura Free',
    ],
    averageRating: 9.6,
    reviewCount: 56,
    description: 'An intimate, avant-garde tapestry of heartbreak, memory, and youth.',
  },
  {
    id: 'album-ok-computer',
    title: 'OK Computer',
    artist: ['Radiohead'],
    releaseDate: new Date('1997-05-21'),
    releaseYear: 1997,
    length: '53:21',
    numSongs: 12,
    genres: ['Alternative Rock', 'Art Rock', 'Progressive Rock'],
    coverImageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'Airbag',
      'Paranoid Android',
      'Subterranean Homesick Alien',
      'Exit Music (For a Film)',
      'Let Down',
      'Karma Police',
      'Fitter Happier',
      'Electioneering',
      'Climbing Up the Walls',
      'No Surprises',
      'Lucky',
      'The Tourist',
    ],
    averageRating: 9.5,
    reviewCount: 38,
    description: 'A prescient portrait of technological alienation and modern existential dread.',
  },
  {
    id: 'album-ram',
    title: 'Random Access Memories',
    artist: ['Daft Punk'],
    releaseDate: new Date('2013-05-17'),
    releaseYear: 2013,
    length: '74:24',
    numSongs: 13,
    genres: ['Electronic', 'Disco', 'Funk', 'Synth-pop'],
    coverImageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'Give Life Back to Music',
      'The Game of Love',
      'Giorgio by Moroder',
      'Within',
      'Instant Crush',
      'Lose Yourself to Dance',
      'Touch',
      'Get Lucky',
      'Beyond',
      'Motherboard',
      'Fragments of Time',
      'Doin\' It Right',
      'Contact',
    ],
    averageRating: 9.3,
    reviewCount: 45,
    description: 'A sumptuous tribute to late-1970s and early-1980s American dance music and live instrumentation.',
  },
  {
    id: 'album-dsotm',
    title: 'The Dark Side of the Moon',
    artist: ['Pink Floyd'],
    releaseDate: new Date('1973-03-01'),
    releaseYear: 1973,
    length: '42:50',
    numSongs: 10,
    genres: ['Progressive Rock', 'Psychedelic Rock', 'Art Rock'],
    coverImageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'Speak to Me',
      'Breathe (In the Air)',
      'On the Run',
      'Time',
      'The Great Gig in the Sky',
      'Money',
      'Us and Them',
      'Any Colour You Like',
      'Brain Damage',
      'Eclipse',
    ],
    averageRating: 9.7,
    reviewCount: 64,
    description: 'The monumental concept album examining passage of time, greed, conflict, and mental strain.',
  },
  {
    id: 'album-igor',
    title: 'IGOR',
    artist: ['Tyler, the Creator'],
    releaseDate: new Date('2019-05-17'),
    releaseYear: 2019,
    length: '39:43',
    numSongs: 12,
    genres: ['Neo-Soul', 'Hip Hop', 'Funk', 'Indie Pop'],
    coverImageUrl: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'IGOR\'S THEME',
      'EARFQUAKE',
      'I THINK',
      'EXACTLY WHAT YOU RUN FROM YOU END UP CHASING',
      'RUNNING OUT OF TIME',
      'NEW MAGIC WAND',
      'A BOY IS A GUN*',
      'PUPPET',
      'WHAT\'S GOOD',
      'GONE, GONE / THANK YOU',
      'I DON\'T LOVE YOU ANYMORE',
      'ARE WE STILL FRIENDS?',
    ],
    averageRating: 9.2,
    reviewCount: 39,
    description: 'A vibrant emotional rollercoaster of heartbreak, unrequited love, and genre-defying production.',
  },
  {
    id: 'album-currents',
    title: 'Currents',
    artist: ['Tame Impala'],
    releaseDate: new Date('2015-07-17'),
    releaseYear: 2015,
    length: '51:06',
    numSongs: 13,
    genres: ['Psychedelic Pop', 'Synth-pop', 'Indie Rock', 'Disco'],
    coverImageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'Let It Happen',
      'Nangs',
      'The Moment',
      'Yes I\'m Changing',
      'Eventually',
      'Gossip',
      'The Less I Know the Better',
      'Past Life',
      'Disciples',
      'Cause I\'m a Man',
      'Reality in Motion',
      'Love/Paranoia',
      'New Person, Same Old Mistakes',
    ],
    averageRating: 9.1,
    reviewCount: 51,
    description: 'Kevin Parker\'s psychedelic synth odyssey exploring personal transformation and moving on.',
  },
  {
    id: 'album-sos',
    title: 'SOS',
    artist: ['SZA'],
    releaseDate: new Date('2022-12-09'),
    releaseYear: 2022,
    length: '67:51',
    numSongs: 23,
    genres: ['R&B', 'Contemporary R&B', 'Pop', 'Hip Hop'],
    coverImageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    tracklist: [
      'SOS',
      'Kill Bill',
      'Seek & Destroy',
      'Low',
      'Love Language',
      'Blind',
      'Used',
      'Snooze',
      'Notice Me',
      'Gone Girl',
      'Smoking on My Ex Pack',
      'Ghost in the Machine',
      'F2F',
      'Nobody Gets Me',
      'Special',
      'Too Late',
      'Far',
      'Shirt',
      'Open Arms',
      'I Hate U',
      'Good Days',
      'Forgiveless',
    ],
    averageRating: 8.9,
    reviewCount: 33,
    description: 'An expansive, raw diary of self-doubt, revenge, and emotional liberation.',
  },
]
