export interface SampleAlbum {
  id: string
  title: string
  artist: string[]
  releaseDate: Date
  releaseYear: number
  length: string
  numSongs: number
  genres: string[]
  coverImageUrl: string
  tracklist: string[]
  description?: string
  averageRating?: number
  reviewCount?: number
}

export const SAMPLE_ALBUMS: SampleAlbum[] = [
  {
    id: 'itunes-1440871877',
    title: 'To Pimp a Butterfly',
    artist: ['Kendrick Lamar'],
    releaseDate: new Date('2015-03-15'),
    releaseYear: 2015,
    length: '78:51',
    numSongs: 16,
    genres: ['Hip-Hop/Rap', 'Jazz Rap', 'Funk'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/b5/a6/91/b5a69171-5232-3d5b-9c15-8963802f83dd/15UMGIM15814.rgb.jpg/600x600bb.jpg',
    tracklist: [
      'Wesley\'s Theory',
      'For Free? (Interlude)',
      'King Kunta',
      'Institutionalized',
      'These Walls',
      'u',
      'Alright',
      'For Sale? (Interlude)',
      'Momma',
      'Hood Politics',
      'How Much a Dollar Cost',
      'Complexion (A Zulu Love)',
      'The Blacker the Berry',
      'You Ain\'t Gotta Lie (Momma Said)',
      'i',
      'Mortal Man',
    ],
    averageRating: 9.8,
    reviewCount: 42,
    description: 'A sprawling masterpiece of modern jazz rap, exploring race, survivor guilt, and self-worth.',
  },
  {
    id: 'itunes-1109714933',
    title: 'In Rainbows',
    artist: ['Radiohead'],
    releaseDate: new Date('2007-10-10'),
    releaseYear: 2007,
    length: '42:39',
    numSongs: 10,
    genres: ['Alternative', 'Art Rock', 'Indie Rock'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/dd/50/c7/dd50c790-99ac-d3d0-5ab8-e3891fb8fd52/634904032463.png/600x600bb.jpg',
    tracklist: [
      '15 Step',
      'Bodysnatchers',
      'Nude',
      'Weird Fishes/Arpeggi',
      'All I Need',
      'Faust Arp',
      'Reckoner',
      'House of Cards',
      'Jigsaw Falling Into Place',
      'Videotape',
    ],
    averageRating: 9.6,
    reviewCount: 56,
    description: 'An intimate, warm sonic tapestry blending electronic textures with sublime acoustic instrumentation.',
  },
  {
    id: 'itunes-1097861387',
    title: 'OK Computer',
    artist: ['Radiohead'],
    releaseDate: new Date('1997-05-21'),
    releaseYear: 1997,
    length: '53:21',
    numSongs: 12,
    genres: ['Alternative', 'Art Rock', 'Progressive Rock'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/07/60/ba/0760ba0f-148c-b18f-d0ff-169ee96f3af5/634904078164.png/600x600bb.jpg',
    tracklist: [
      'Airbag',
      'Paranoid Android',
      'Subterranean Homesick Alien',
      'Exit Music (For a Film)',
      'Let Down',
      'Karma Police',
      'Fitter Happier',
      'Electioneering',
      'Climbing Up the Walls',
      'No Surprises',
      'Lucky',
      'The Tourist',
    ],
    averageRating: 9.5,
    reviewCount: 38,
    description: 'A prescient portrait of technological alienation and modern existential dread.',
  },
  {
    id: 'itunes-617154241',
    title: 'Random Access Memories',
    artist: ['Daft Punk'],
    releaseDate: new Date('2013-05-17'),
    releaseYear: 2013,
    length: '74:24',
    numSongs: 13,
    genres: ['Dance', 'Electronic', 'Disco', 'Funk'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/e8/43/5f/e8435ffa-b6b9-b171-40ab-4ff3959ab661/886443919266.jpg/600x600bb.jpg',
    tracklist: [
      'Give Life Back to Music',
      'The Game of Love',
      'Giorgio by Moroder',
      'Within',
      'Instant Crush',
      'Lose Yourself to Dance',
      'Touch',
      'Get Lucky',
      'Beyond',
      'Motherboard',
      'Fragments of Time',
      'Doin\' It Right',
      'Contact',
    ],
    averageRating: 9.3,
    reviewCount: 45,
    description: 'A sumptuous tribute to late-1970s and early-1980s American dance music and live instrumentation.',
  },
  {
    id: 'itunes-1065975633',
    title: 'The Wall',
    artist: ['Pink Floyd'],
    releaseDate: new Date('1979-11-30'),
    releaseYear: 1979,
    length: '81:08',
    numSongs: 26,
    genres: ['Rock', 'Progressive Rock', 'Art Rock'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/3e/17/ec/3e17ec6d-f980-c64f-19e0-a6fd8bbf0c10/886445635850.jpg/600x600bb.jpg',
    tracklist: [
      'In the Flesh?',
      'The Thin Ice',
      'Another Brick in the Wall, Pt. 1',
      'The Happiest Days of Our Lives',
      'Another Brick in the Wall, Pt. 2',
      'Mother',
      'Goodbye Blue Sky',
      'Empty Spaces',
      'Young Lust',
      'One of My Turns',
      'Don\'t Leave Me Now',
      'Another Brick in the Wall, Pt. 3',
      'Goodbye Cruel World',
      'Hey You',
      'Is There Anybody Out There?',
      'Nobody Home',
      'Vera',
      'Bring the Boys Back Home',
      'Comfortably Numb',
      'The Show Must Go On',
      'In the Flesh',
      'Run Like Hell',
      'Waiting for the Worms',
      'Stop',
      'The Trial',
      'Outside the Wall',
    ],
    averageRating: 9.7,
    reviewCount: 64,
    description: 'The monumental rock opera examining isolation, society, and mental strain.',
  },
  {
    id: 'itunes-1658650093',
    title: 'SOS',
    artist: ['SZA'],
    releaseDate: new Date('2022-12-09'),
    releaseYear: 2022,
    length: '67:51',
    numSongs: 23,
    genres: ['R&B/Soul', 'Pop', 'Contemporary R&B'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/62/93/13/6293132e-20ff-67ab-3d1f-96bb6797a6ba/196589564955.jpg/600x600bb.jpg',
    tracklist: [
      'SOS',
      'Kill Bill',
      'Seek & Destroy',
      'Low',
      'Love Language',
      'Blind',
      'Used',
      'Snooze',
      'Notice Me',
      'Gone Girl',
      'Smoking on My Ex Pack',
      'Ghost in the Machine',
      'F2F',
      'Nobody Gets Me',
      'Special',
      'Too Late',
      'Far',
      'Shirt',
      'Open Arms',
      'I Hate U',
      'Good Days',
      'Forgiveless',
    ],
    averageRating: 9.1,
    reviewCount: 43,
    description: 'An expansive, raw diary of self-doubt, revenge, and emotional liberation.',
  },
  {
    id: 'itunes-1474815798',
    title: 'Abbey Road (2019 Mix)',
    artist: ['The Beatles'],
    releaseDate: new Date('1969-09-26'),
    releaseYear: 1969,
    length: '47:29',
    numSongs: 17,
    genres: ['Rock', 'Classic Rock', 'Pop'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/48/53/43/485343e3-dd6a-0034-faec-f4b6403f8108/13UMGIM63890.rgb.jpg/600x600bb.jpg',
    tracklist: [
      'Come Together',
      'Something',
      'Maxwell\'s Silver Hammer',
      'Oh! Darling',
      'Octopus\'s Garden',
      'I Want You (She\'s So Heavy)',
      'Here Comes the Sun',
      'Because',
      'You Never Give Me Your Money',
      'Sun King',
      'Mean Mr. Mustard',
      'Polythene Pam',
      'She Came in Through the Bathroom Window',
      'Golden Slumbers',
      'Carry That Weight',
      'The End',
      'Her Majesty',
    ],
    averageRating: 9.7,
    reviewCount: 58,
    description: 'The defining final recorded masterpiece of The Beatles, featuring the legendary B-side medley.',
  },
  {
    id: 'itunes-594061854',
    title: 'Rumours',
    artist: ['Fleetwood Mac'],
    releaseDate: new Date('1977-02-04'),
    releaseYear: 1977,
    length: '39:43',
    numSongs: 11,
    genres: ['Rock', 'Soft Rock', 'Pop'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/4d/13/ba/4d13bac3-d3d5-7581-2c74-034219eadf2b/081227970949.jpg/600x600bb.jpg',
    tracklist: [
      'Second Hand News',
      'Dreams',
      'Never Going Back Again',
      'Don\'t Stop',
      'Go Your Own Way',
      'Songbird',
      'The Chain',
      'You Make Loving Fun',
      'I Don\'t Want to Know',
      'Oh Daddy',
      'Gold Dust Woman',
    ],
    averageRating: 9.6,
    reviewCount: 51,
    description: 'A timeless, turbulent monument to love, heartbreak, and emotional transparency.',
  },
  {
    id: 'itunes-1528111535',
    title: 'folklore (deluxe version)',
    artist: ['Taylor Swift'],
    releaseDate: new Date('2020-07-24'),
    releaseYear: 2020,
    length: '67:03',
    numSongs: 17,
    genres: ['Alternative', 'Indie Folk', 'Pop'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/8c/ef/c2/8cefc23a-61b7-05ff-b52a-bb1e4922087c/20UMGIM64216.rgb.jpg/600x600bb.jpg',
    tracklist: [
      'the 1',
      'cardigan',
      'the last great american dynasty',
      'exile (feat. Bon Iver)',
      'my tears ricochet',
      'mirrorball',
      'seven',
      'august',
      'this is me trying',
      'illicit affairs',
      'invisible string',
      'mad woman',
      'epiphany',
      'betty',
      'peace',
      'hoax',
      'the lakes',
    ],
    averageRating: 9.3,
    reviewCount: 47,
    description: 'A moody, introspective chamber-pop and indie-folk escape crafted during quarantine.',
  },
  {
    id: 'itunes-1739659134',
    title: 'HIT ME HARD AND SOFT',
    artist: ['Billie Eilish'],
    releaseDate: new Date('2024-05-17'),
    releaseYear: 2024,
    length: '43:45',
    numSongs: 10,
    genres: ['Alternative', 'Pop'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/da/bf/19/dabf1947-68be-35f1-39fe-c6f373eb49dc/24UMGIM22306.rgb.jpg/600x600bb.jpg',
    tracklist: [
      'SKINNY',
      'LUNCH',
      'CHIHIRO',
      'BIRDS OF A FEATHER',
      'WILDFLOWER',
      'THE GREATEST',
      'L\'AMOUR DE MA VIE',
      'THE DINER',
      'BITTERSUITE',
      'BLUE',
    ],
    averageRating: 9.2,
    reviewCount: 39,
    description: 'A dynamic, cinematic dive into identity, heartbreak, and emotional vulnerability.',
  },
  {
    id: 'itunes-697194953',
    title: 'Discovery',
    artist: ['Daft Punk'],
    releaseDate: new Date('2001-03-12'),
    releaseYear: 2001,
    length: '60:50',
    numSongs: 14,
    genres: ['Dance', 'Electronic', 'House'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/fd/4a/77/fd4a77db-0ebc-d043-41a2-f32fa1bb0fb4/dj.qrikkdwj.jpg/600x600bb.jpg',
    tracklist: [
      'One More Time',
      'Aerodynamic',
      'Digital Love',
      'Harder, Better, Faster, Stronger',
      'Crescendolls',
      'Nightvision',
      'Superheroes',
      'High Life',
      'Something About Us',
      'Voyager',
      'Veridis Quo',
      'Short Circuit',
      'Face to Face',
      'Too Long',
    ],
    averageRating: 9.6,
    reviewCount: 53,
    description: 'The revolutionary French touch disco-space opera that redefined dance music.',
  },
  {
    id: 'itunes-1065973975',
    title: 'Wish You Were Here',
    artist: ['Pink Floyd'],
    releaseDate: new Date('1975-09-12'),
    releaseYear: 1975,
    length: '44:28',
    numSongs: 5,
    genres: ['Rock', 'Progressive Rock', 'Psychedelic'],
    coverImageUrl: 'https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/91/9f/fa/919ffaf8-c419-74d6-848e-f5ea2543f497/886445635812.jpg/600x600bb.jpg',
    tracklist: [
      'Shine On You Crazy Diamond (Pts. 1-5)',
      'Welcome to the Machine',
      'Have a Cigar',
      'Wish You Were Here',
      'Shine On You Crazy Diamond (Pts. 6-9)',
    ],
    averageRating: 9.8,
    reviewCount: 61,
    description: 'An emotional tribute to Syd Barrett and a scathing critique of the music industry.',
  },
]
